FROM data6s/airflow_with_spark:latest

ARG root_password
ENV MONGODB_ROOT_PASSWORD $root_password

USER root
COPY --chown=airflow:root ./dags .
COPY --chown=airflow:root ./constants.py ./dags
USER airflow

RUN pip install -r requirements.txt 
