FROM python:3.10.9

RUN pip install mlflow
RUN mkdir /mlflow

ENTRYPOINT  mkdir -p $ARTIFACT_ROOT && \
            mkdir -p $BACKEND_STORE_URI && \
            \
            mlflow server \
            --backend-store-uri $BACKEND_STORE_URI \
            --default-artifact-root $ARTIFACT_ROOT \
            --host 0.0.0.0
