FROM apache/airflow:2.4.2

ARG root_password
ENV MONGODB_ROOT_PASSWORD $root_password

USER root
COPY --chown=airflow:root ./dags .
COPY --chown=airflow:root ./constants.py ./dags
USER airflow

RUN pip install -r requirements.txt 
