FROM apache/spark-py:v3.2.2

USER 0
ARG root_password
ENV MONGODB_ROOT_PASSWORD $root_password
RUN pip install pymongo pandas
COPY ./spark-local .
COPY ./constants.py .
#COPY ./pi.py /opt/spark/examples/src/main/python/pii.py
USER 185

#ENTRYPOINT ["/opt/spark/bin/spark-submit", "/opt/spark/work-dir/main.py"]
#"/opt/spark/work-dir/main.py"
