apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-configmap
data:
  # Artifacts will be stored locally in the pod, same goes for backend storage
  ARTIFACT_STORE: /mlflow/artifacts
  BACLKEND_STORE_URI: sqlite:///mlflow/db/db.db
