apiVersion: v1
kind: Service
metadata:
  labels:
    app: mlflow-tracking-app
  name: mlflow-tracking
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: mlflow-tracking-app
